### PR TITLE
falling back to sbt 0.13.5 and reverting sbt utils to 2.1.0

### PR DESCRIPTION
**Pull request by nfma**

### CODE REVIEW

**Comment by duncancrawford** [comment]
why?

**Comment by nfma** [comment]
So that we can unblock one of our stories, it’s not that we think this is the way forward, but given that we need to get *a* version of simple-reactivemongo with the fix out, we will revert this change as soon as we are ready to upgrade the pgp-plugin.


—

**Comment by duncancrawford** [comment]
i believe @charleskubicek has resolved the publishing issues

**Comment by nfma** [comment]
He as the one sugesting this temporary solution



—

**Comment by duncancrawford** [comment]
I have done it manually for now

**Pull request closed without merging**
