### PR TITLE
Reactive repository paging

### PR DESCRIPTION
**Pull request by NTCoding**
My name is Nick and I paired on this with Ross McCorkindale. We are working with the VOA and were advised to use this library which we found useful. However, it didn't provide the ability to page which we needed.

Please let us know if you want us to make any changes. We've listed some of the design trade-offs we considered below.

Design Trade-offs
~~~~~~~~~~~~~~
1. We added findAllPaged and findPaged to ReactiveRepository. Ideally we would have updated the Repository interface and made the the page and pageSize parameters optional. We decided to present you with this less-invasive approach first to get your feedback.

2. We used FeatureSpec rather than WordSpec for the tests because we wanted to test a variety of combinations and we felt FeatureSpec would allow us to express this more cleanly. We probably could bash WordSpec into shape if you prefer consistency.

3. We put the tests in a new file because the existing test file was already 250 lines long. We didn't want the test files to become huge and impact their ability to express behaviours.

4. In our test file we re-used a lot of the test helpers from the existing test file. However, we did add some of our own test data and helper methods which we put at the bottom of the test file so that would could accentuate the behaviours of the class we were testing; when someone comes to look at the file, the first thing they see is the behaviours and then they can drill down into the mechanics of the tests.

### CODE REVIEW

**Comment by duncancrawford** [comment]
@pacenick when you have some time can you review this?

**Comment by pacenick** [comment]
Using QueryOpts and skipN in the find operations can result in expensive CPU usage on mongo. The QueryOpts helper under the hood will use cursor.skip()!

Please see the following links...
http://docs.mongodb.org/manual/reference/method/cursor.skip/#cursor.skip
http://blog.mongodirector.com/fast-paging-with-mongodb/

Instead of using QueryOpts and skip, an alternative solution could be to pass the BSONObjectId offset to the paging functions, replacing the skip parameter. Please see this link concerning http://www.quora.com/How-can-I-do-pagination-with-MongoDB-ObjectId-as-key.

**Comment by NTCoding** [comment]
Hi @pacenick,

Thanks for the advice. That's definitely a substantial problem which voids our proposed changes.

I think your suggestion allows for "next-page" style functionality, but won't allow you to jump straight to a particular page e.g. page 50. That's acceptable for our current needs though and its hard to think of a scenario where that wouldn't suffice.

If you want an excuse to write a coordinator algorithm or implement paxos we could always create a library where IDs are sequentially generated :laughing:

**Comment by NTCoding** [comment]
Btw, not sure when we'll have time for this, but if you're happy with the the proposed solution we'll do it at some point.

**Comment by pacenick** [comment]
Hi @NTCoding , 

Happy with the solution being used temporarily in your own code base but before this PR can be merged, the performance part will need to be resolved.

**Comment by agilestevesmith** [comment]
Hi @NTCoding, based on @duncancrawford's closing of https://github.com/hmrc/simple-reactivemongo/pull/43 we will close this PR. Thanks again for the suggested changes

**Pull request closed without merging**
